name: arvet-slam-2.0
channels:
  - defaults
  - conda-forge
dependencies:
  - boost
  - eigen
  - h5py
  - numpy
  - matplotlib
  - pillow
  - pip
  - py-opencv
  - pymongo
  - python
  - pyyaml
  - seaborn
  - setuptools
  - suitesparse
  - tqdm
  - wheel
  - pip:
    - mongomock
    - pymodm
    - transforms3d
    - xxhash
    - pykitti
